on: push

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      # maven java
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven version
        run: mvn -v
      - name: maven test
        run: |
          cd java 
          mvn test

  clojure:
    runs-on: ubuntu-latest
    steps:
      # lein clojure
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install lein
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          lein: 2.9.6
      - name: leiningen version
        run: lein -v
      - name: leiningen test
        run: |
          cd clojure
          lein test

  scala:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v11
    - name: test
      run: |
        cd scala
        sbt -v +test


          
      # - name: sbt test
      #   id: sbt
      #   uses: ./scala
      #   with:
      #     commands: test
      #     sbt_project_directory: ./scala/project

  # test-python:
  #   #TODO
  # test-typescript:
  #   #TODO
