on: push

jobs:
  test-jvm:
    runs-on: ubuntu-latest
    steps:
      # maven java
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven version
        run: mvn -v
      - name: maven test
        run: |
          cd java 
          mvn --batch-mode --update-snapshots verify 
          mvn test
          cd ..
      # lein clojure
      - name: install lein
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          lein: 2.9.6
      - name: leiningen version
        run: lein -v
      - name: leiningen test
        run: |
          cd clojure
          lein test
          cd ..
      # sbt scala
      - name: sbt test
        id: sbt
        uses: ./scala
        with:
          commands: test
          sbt_project_directory: ./scala/project

  # test-python:
  #   #TODO
  # test-typescript:
  #   #TODO
