on: push

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      # maven java
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven version
        run: mvn -v
      - name: maven test
        run: |
          cd java 
          mvn test

  clojure:
    runs-on: ubuntu-latest
    steps:
      # lein clojure
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install lein
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          lein: 2.9.6
      - name: leiningen version
        run: lein -v
      - name: leiningen test
        run: |
          cd clojure
          lein test

  scala:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v11
    - name: test
      run: |
        cd scala
        sbt -v +test

  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          cd python/armstrong
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: test python
        run: |
          cd python/test
          python test_armstrong.py

  # test-typescript:
  #   #TODO
