on: push

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      # maven java
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven version
        run: mvn -v
      - name: maven test
        run: |
          cd java 
          mvn --batch-mode --update-snapshots verify 
          mvn test

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      # lein clojure
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install lein
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          lein: 2.9.6
      - name: leiningen version
        run: lein -v
      - name: leiningen test
        run: |
          cd clojure
          lein test
          cd ..

jobs:
  scala:
    runs-on: ubuntu-latest
    steps:
      # sbt scala
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: sbt version
        run: sbt -v
      - name: sbt test
        run: |
          cd scala
          sbt -v +test
          cd ..

      # - name: sbt test
      #   id: sbt
      #   uses: ./scala
      #   with:
      #     commands: test
      #     sbt_project_directory: ./scala/project

  # test-python:
  #   #TODO
  # test-typescript:
  #   #TODO
