on: push

jobs:
  test-jvm:
    runs-on: ubuntu-latest
    steps:
      # - name: checkout
      #   uses: actions/checkout@v2
      # # lein clojure
      # - name: set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      #   # uses: actions/setup-java@v1
      #   # with:
      #   #   java-version: 1.8
      # - name: install lein
      #   uses: DeLaGuardo/setup-clojure@3.4
      #   with:
      #     # Install just one or all simultaneously
      #     #cli: 1.10.1.693 # Clojure CLI based on tools.deps
      #     lein: 2.9.6     # or use 'latest' to always provision latest version of leiningen
      #     #boot: 2.8.3     # or use 'latest' to always provision latest version of boot
      # - name: leiningen version
      #   run: lein -v
      ###############################
      # - name: leiningen test
      #   run: cd clojure && lein test && cd ..
      # maven java
      - uses: actions/checkout@v2
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven test
        run: |
          cd java 
          mvn --batch-mode --update-snapshots verify 
          mvn test
          cd ..
      - name: install lein
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          # Install just one or all simultaneously
          #cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.6     # or use 'latest' to always provision latest version of leiningen
          #boot: 2.8.3     # or use 'latest' to always provision latest version of boot
      - name: leiningen version
        run: lein -v

      # # sbt scala
      # - name: sbt test
      #   id: sbt
      #   uses: ./scala
      #   with:
      #     commands: test
      #     sbt_project_directory: ./scala/project

  # test-python:
  #   #TODO
  # test-typescript:
  #   #TODO
