name: static code analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: detekt - kotlin
        uses: natiginfo/action-detekt-all@1.17.1
      - name: mobsfscan - kotlin
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json'
